name: flutter_ecommerce
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_typeahead: ^4.0.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  http: ^0.13.4
  brasil_fields: ^1.3.1
  get: ^4.6.1
  via_cep: ^1.0.0
  reactive_forms: ^14.1.0
  flutter_easyloading: ^3.0.3
  mobx: ^2.0.6+1
  intl: ^0.17.0
  cool_alert: ^1.0.3
  animated_text_kit: ^4.2.1
  card_swiper: ^2.0.3
  tab_container: ^2.0.0
  chips_choice: ^2.0.1
  pull_to_refresh: ^2.0.0
  video_player: ^2.3.0
  get_storage: ^2.0.3
  dialogs: ^0.0.7
  flutter_credit_card: ^3.0.1
  credit_card_validator: ^2.0.1
  flutter_localizations: 
    sdk: flutter
  encrypt: ^4.1.0
  flutter_native_splash: ^0.3.2
  flutter_launcher_icons: ^0.8.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  intl_translation: ^0.17.1


flutter:
  uses-material-design: true
  assets:
    - images/img_star.png
    - images/load.gif
    - images/mastercard.png
    - images/card_bg.png
    - images/visa.png
    - images/cred.png


  generate: true

dependency_overrides:
  intl: ^0.17.0

flutter_native_splash:
  color: "#FFFFFF"
  image: images/yugioh.png
  android: true
  ios: true

flutter_icons:
  android: "ic_launcher"
  image_path: images/yugioh.png
  ios: true
  remove_alpha_ios: true


flutter_intl:
  enabled: true
  class_name: LocaleProvider
  default_locale: pt